name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-matrix:
    name: Build and test variant ${{ matrix.variant }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        variant:
          - Foss
          - Gplay
      fail-fast: false

    env:
      JAVA_TOOL_OPTIONS: "-Xmx4g"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up mock Firebase config
        run: cp app/mock-google-services.json app/google-services.json

      - name: Build ${{ matrix.variant }}
        run: ./gradlew assemble${{ matrix.variant }}Debug
        env:
          ETCHDROID_ENABLE_SENTRY: ${{ matrix.variant == 'Gplay' }}

      - name: Run unit tests for ${{ matrix.variant }}
        run: ./gradlew test${{ matrix.variant }}UnitTest
        env:
          ETCHDROID_ENABLE_SENTRY: ${{ matrix.variant == 'Gplay' }}
